---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.4
    hooks:
      - id: pylint

  - repo: local
    hooks:
      - id: pytest
        name: pylint
        entry: pytest
        language: python
        types: [python]

  - repo: local
    hooks:
      - id: rule tests
        name: rule tests
        entry: python3 cli.py test
        language: python
        types: [python]
