---
version: '3.9'
services:
  railwayjaguar:
    image: railwayjaguar-railwayjaguar:latest
    build: .
    networks:
      - kafka-backend
    depends_on:
      - broker

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    networks:
      - kafka-backend
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_JMX_PORT: 9101
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log

  broker:
    image: confluentinc/cp-kafka:7.4.0
    networks:
      - default
      - kafka-backend
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://kafka.hackinglab.local:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    volumes:
      - kafka-data:/var/lib/kafka/data

  kafka-exporter:
    image: danielqsj/kafka-exporter:v1.6.0
    command: --kafka.server=broker:29092
    networks:
      - metrics-backend
      - kafka-backend
    depends_on:
      - broker

  prometheus:
    image: prom/prometheus:v2.43.1
    networks:
      - metrics-backend
      - kafka-backend
    configs:
      - source: prom_config
        target: /etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:9.5.2-ubuntu
    networks:
      - default
      - metrics-backend
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana


networks:
  metrics-backend:
  kafka-backend:

configs:
  prom_config:
    file: ./conf/prometheus/prometheus.yml

volumes:
  prometheus-data:
  grafana-data:
  kafka-data:
  zookeeper-data:
  zookeeper-logs:
