global:
  scrape_interval:     15s
  evaluation_interval: 5s

# Scrape configs only contain one scrape target
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["railwayjaguar:8000"]
  - job_name: kafka
    static_configs:
      - targets: [
          "kafka-exporter:9308",
          "broker:9101",
          "zookeeper:9101",
        ]